[package]
name = "stremio-core"
version = "0.1.0"
authors = ["Smart Code OOD"]
edition = "2018"

[workspace]
members = [
    "stremio-derive",
    "stremio-analytics",
    "stremio-watched-bitfield",
]

[lib]
doctest = false

[features]
env-future-send = []

[dependencies]
stremio-derive = { path = "stremio-derive" }
stremio-watched-bitfield = { path = "stremio-watched-bitfield" }
stremio-official-addons = "=2.0.10"
serde = "1.0.*"
serde_json = "1.0.*"
serde_url_params = "0.2.*"
stremio-serde-hex = "0.1.*" # keep track of https://github.com/fspmarshall/serde-hex/pull/8
serde_with = { version = "1.14.*", features = ["macros", "chrono"] }
flate2 = "1.0.*"
futures = "0.3.*"
http = "0.2.*"
url = { version = "2.2.*", features = ["serde"] }
percent-encoding = "2.1.*"
chrono = { version = "0.4.*", features = ["serde"] }
semver = { version = "0.11.*", features = ["serde"] }
base64 = "0.13.*"
either = "1.6.*"
enclose = "1.1.*"
derivative = "2.2.*"
derive_more = "0.99.*"
boolinator = "2.4.*"
strum = "0.22.*"
strum_macros = "0.22.*"
lazysort = "0.2.*"
lazy_static = "1.4.*"
itertools = "0.10.*"
magnet-url = "2.0.*"
hex = "0.4.*"
anyhow = "1.0.*"

[dev-dependencies]
tokio = { version = "1.12.*", features = ["rt"] }
tokio-current-thread = "=0.2.0-alpha.1"
serde_test = "1.0.*"
assert_matches = "1.5.*"
